### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by sbellver** [tng10/vue3-signature-pad#3]
hi Julio!

I trying to install your Vue3 signature pad into quasar framework, but no success.

After yarn install vue3-signature-pad all seems ok, and If I search under node_modules the folder vue3-signature-pad exists.

But when I try to make a boot file with 

```
import SignaturePad from 'vue3-signature-pad';
export default async ({ app }) => {
  app.use(SignaturePad);
};
```

And then, quasar always say:

```
ERROR  Failed to compile with 1 errors
This dependency was not found:
* vue3-signature-pad in ./src/boot/signaturepad.js
To install it, you can run: npm install --save vue3-signature-pad
```

If I delete node_modules and then run  npm install --save vue3-signature-pad && npm I , same error happens

**Comment by sbellver** [comment]
Not sure, but using the original repo, if we change createForm by h , it works. 

I think the problem is about dependencies from 6pm / yarn at package.json. Was not installed all.

**Comment by tng10** [comment]
Hi @sbellver 

I am not familiar with Quasar Framework, but it seems this has to do with Vue3

as mentioned in the docs (https://quasar.dev/quasar-cli/boot-files)

> A common use case for Quasar applications is to **run code before the root Vue app instance is instantiated**, like injecting and initializing your own dependencies (examples: Vue components, libraries…) or simply configuring some startup code of your app.

However on Vue3 (https://v3.vuejs.org/guide/instance.html#creating-an-application-instance)

> Every Vue application starts by creating a new application instance with the createApp function

> The application instance is used to register 'globals' that can then be used by components within that application

It might be the case those `boot files` are not supported on Vue3
